exp_name: _400_epochs_NEW
mode: train

model:
  name: bim_vfi
  args:
    pyr_level: 3
    feat_channels: 32

train_dataset:
  name: vimeo
  args:
    root_path: ../data/vimeo_triplet
    split: train
    patch_size: 128        # ↓ nhỏ hơn 256 để giảm VRAM
  loader:
    batch_size: 32          # ↓ 4 ảnh/iter cho GPU 4 GB
    num_workers: 8         # ↓ để tránh quá tải CPU

test_dataset:
  name: vimeo
  args:
    root_path: ../data/vimeo_triplet
    split: val
  loader:
    batch_size: 32
    num_workers: 8
  save_imgs: False

optimizer:
  name: adamW
  args:
    lr: 5.0e-5
    weight_decay: 5.0e-5

lr_scheduler:
  name: step_lr
  args:
    step_size: 25           # Giảm LR mỗi 25 epoch
    gamma: 0.8              # Nhân LR với hệ số 0.8

gradient_clip: 1

loss:
  - { name: multiple_charbonnier, args: { weight: 1, gamma: 0.25 } }
  - { name: multiple_ternary,     args: { weight: 1, gamma: 0.25 } }
  - { name: photo_teacher,        args: { weight: 1, gamma: 0.25 } }
  - { name: flow_distill_res,     args: { weight: 0.005, beta: 1, gamma: 0.5 } }
  - { name: flow_teacher_reg,     args: { weight: 0.005, gamma: 0.5 } }
  - { name: flow_smooth_tea1,     args: { weight: 0.05, gamma: 0.5, weight_type: gaussian, edge_constant: 150 } }

max_epoch: 23              
validate_every: 10          # Validate 10 epoch/lần
save_every: 10              # Lưu checkpoint 10 epoch/lần
vis_every: 10               # Không cần visualize (giảm thời gian)
seed: 1234
dist_url: env://

# ADD: Early stopping configuration
enable_early_stopping: true        # Set to true to enable early stopping
early_stopping_patience: 3       