exp_name: _300_epochs
mode: train
resume: save/bim_vfi_train__100_epochs/checkpoints/model_best.pth

model:
  name: bim_vfi
  args:
    pyr_level: 3
    feat_channels: 32

train_dataset:
  name: vimeo
  args:
    root_path: C:/Users/ZVC/Downloads/Crucial/CS420/BiM-VFI/data/vimeo_triplet
    split: train
    patch_size: 128        # ↓ nhỏ hơn 256 để giảm VRAM
  loader:
    batch_size: 4          # ↓ 4 ảnh/iter cho GPU 4 GB
    num_workers: 2         # ↓ để tránh quá tải CPU

test_dataset:
  name: vimeo
  args:
    root_path: C:/Users/ZVC/Downloads/Crucial/CS420/BiM-VFI/data/vimeo_triplet
    split: val
  loader:
    batch_size: 4
    num_workers: 1
  save_imgs: False

optimizer:
  name: adamW
  args:
    lr: 2.0e-5
    weight_decay: 5.0e-5

lr_scheduler:
  name: one_cycle_lr          
  args:
    max_lr: 5.0e-5           # Peak LR (lower than original)
    pct_start: 0.1           # 10% warmup
    cycle_momentum: False
    anneal_strategy: cos

gradient_clip: 1

loss:
  - { name: multiple_charbonnier, args: { weight: 1, gamma: 0.25 } }
  - { name: multiple_ternary,     args: { weight: 1, gamma: 0.25 } }
  - { name: photo_teacher,        args: { weight: 1, gamma: 0.25 } }
  - { name: flow_distill_res,     args: { weight: 0.005, beta: 1, gamma: 0.5 } }
  - { name: flow_teacher_reg,     args: { weight: 0.005, gamma: 0.5 } }
  - { name: flow_smooth_tea1,     args: { weight: 0.05, gamma: 0.5, weight_type: gaussian, edge_constant: 150 } }

max_epoch: 300              # ↓ Train thử trước 50 epoch (có thể tăng sau)
validate_every: 5          # Validate 5 epoch/lần
save_every: 5              # Lưu checkpoint 5 epoch/lần
vis_every: 10               # Không cần visualize (giảm thời gian)
seed: 1234
dist_url: env://

# ADD: Early stopping configuration
enable_early_stopping: true        # Set to true to enable early stopping
early_stopping_patience: 3        # Stop if no improvement for 10 epochs